say:
  generate:
    do: "nu mise-lazybox.nu -f"
  lint:
    do: "nu mise-lazybox.test.nu"
  build:
    do: "docker build --target lazybox -t bonisoft3/lazybox ."
  test:
    do: "docker build --target lazybox-builder ."
