services:
  launch:
    build:
      target: nubox
    command: nu -l

  integrate:
    build:
      target: lazybox
    command: sh -c "jq --version && yq --version && bat --version && rg --version && echo 'All tools OK'"

  lazybox:
    build:
      target: lazybox

  lazybox-alpine:
    build:
      target: lazybox
      args:
        BASE_IMG: alpine/curl

  lazybox-wolfi:
    build:
      target: lazybox
      args:
        BASE_IMG: chainguard/wolfi-base

  bbcurl:
    build:
      target: bbcurl

  bbcurl-windows:
    build:
      dockerfile: windows.Dockerfile
      target: bbcurl-windows
