services:
  launch:
    build:
      target: nubox
    command: nu -l

  integrate:
    build:
      target: nubox
      args:
        BASE_IMG: mcr.microsoft.com/devcontainers/base:ubuntu24.04@sha256:4bcb1b466771b1ba1ea110e2a27daea2f6093f9527fb75ee59703ec89b5561cb
    command: nu -l -c "mise --version; jq --version; yq --version; bat --version; rg --version; echo 'All tools OK'"

  lazybox:
    build:
      target: lazybox

  lazybox-alpine:
    build:
      target: lazybox
      args:
        BASE_IMG: alpine/curl@sha256:5bd4985f3daa6d1ca87619802190afc24c0ccd410b1f123de5afc8e891b5fc71

  lazybox-wolfi:
    build:
      target: lazybox
      args:
        BASE_IMG: chainguard/wolfi-base@sha256:a5a619c1793039dcf92f02178f37c94bb3d6001403716da59d6092dfe8d9b502

  bbcurl:
    build:
      target: bbcurl

  bbcurl-windows:
    build:
      dockerfile: windows.Dockerfile
      target: bbcurl-windows
