services:
  lazybox:
    build:
      target: lazybox

  lazybox-alpine:
    build:
      target: lazybox
      args:
        BASE_IMG: alpine/curl

  lazybox-wolfi:
    build:
      target: lazybox
      args:
        BASE_IMG: chainguard/wolfi-base

  bbcurl:
    build:
      target: bbcurl

  bbcurl-windows:
    build:
      dockerfile: windows.Dockerfile
      target: bbcurl-windows
