#!/bin/sh
# Get the directory where this script lives
DIR="$(dirname "$(readlink -f "$0")")" 

# Run mise tool-stub with trusted config
"$DIR/../libexec/lazy-mise" trust -y -a -q .
MISE_LOCKED=0 exec "$DIR/../libexec/lazy-mise" tool-stub "$DIR/helm.toml" "$@"
