#!/bin/sh
# Get the directory where this script lives
DIR="$(dirname "$(readlink -f "$0")")" 

# Run mise tool-stub with trusted config
"$DIR/.lazybox" trust -y -a -q .
MISE_LOCKED=0 exec "$DIR/.lazybox" tool-stub "$DIR/kubectl.toml" "$@"
